version: '3.8'

services:
  tc-app:
    image: ${APP_NAME}:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${APP_PORT}
    container_name: ${APP_NAME}
    depends_on:
      - mysql-db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    command: poetry run uvicorn src.app:app --host 0.0.0.0 --port ${APP_PORT}
  mysql-db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
