"""add relationship order orderitem

Revision ID: 1ec56060d33c
Revises: 073b2a3aab27
Create Date: 2025-01-15 22:30:20.297258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec56060d33c'
down_revision: Union[str, None] = '073b2a3aab27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'order_id')
    # ### end Alembic commands ###
