"""add relationship order orderitem

Revision ID: 1ec56060d33c
Revises: 073b2a3aab27
Create Date: 2025-01-15 22:30:20.297258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec56060d33c'
down_revision: Union[str, None] = '073b2a3aab27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define um nome para a constraint
fk_name = 'fk_order_items_order_id'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        # Usa o nome definido e batch_op
        batch_op.create_foreign_key(fk_name, 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        # Usa o nome definido e batch_op
        batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.drop_column('order_id')
    # ### end Alembic commands ###