"""Update new field inactivated_at from from base_entity

Revision ID: 6787f5df0f04
Revises: 342410eab0f3
Create Date: 2024-12-28 21:58:49.712912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6787f5df0f04'
down_revision: Union[str, None] = '342410eab0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('inactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('inactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'inactivated_at')
    op.drop_column('categories', 'inactivated_at')
    # ### end Alembic commands ###
