"""Add entity permission

Revision ID: 898b4cf28b7e
Revises: d4cfda9a0fb4
Create Date: 2024-12-25 18:02:04.493549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898b4cf28b7e'
down_revision: Union[str, None] = 'd4cfda9a0fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
