"""Link order and payment directly

Revision ID: a95708419da2
Revises: 7999a8f4533f
Create Date: 2025-01-21 21:44:11.725559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95708419da2'
down_revision: Union[str, None] = '7999a8f4533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


fk_name = 'fk_orders_id_payment'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_payment', sa.Integer(), nullable=True))
        # Usa batch_op e o nome definido
        batch_op.create_foreign_key(fk_name, 'payments', ['id_payment'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.drop_column('id_payment')
    # ### end Alembic commands ###
