"""Link order and payment directly

Revision ID: a95708419da2
Revises: 7999a8f4533f
Create Date: 2025-01-21 21:44:11.725559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95708419da2'
down_revision: Union[str, None] = '7999a8f4533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id_payment', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_id_payment', 'orders', 'payments', ['id_payment'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_id_payment', 'orders', type_='foreignkey')
    op.drop_column('orders', 'id_payment')
    # ### end Alembic commands ###
