"""Make Permission name unique

Revision ID: d930883ec3eb
Revises: 7ec60bc425de
Create Date: 2024-12-30 22:39:40.100916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd930883ec3eb'
down_revision: Union[str, None] = '7ec60bc425de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define um nome para a constraint
constraint_name = 'uq_permissions_name'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        # Usa o nome definido
        batch_op.create_unique_constraint(constraint_name, ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        # Usa o mesmo nome para remover
        batch_op.drop_constraint(constraint_name, type_='unique')
    # ### end Alembic commands ###