"""Payment qrcode and trasaction_id

Revision ID: ebc6becdb53f
Revises: a95708419da2
Create Date: 2025-01-22 07:31:10.040438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebc6becdb53f'
down_revision: Union[str, None] = 'a95708419da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('qr_code', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'qr_code')
    # ### end Alembic commands ###
