apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenger-pod
  labels:
    app: tech-challenger-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenger-pod
  template:
    metadata:
      labels:
        app: tech-challenger-pod
    spec:
      containers:
      - name: tech-challenger-app
        image: kiyoshinoue/tech-challenger-app:1.5
        ports:
        - containerPort: 8000
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/health
        #     port: 80000
        #     scheme: HTTPS
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   initialDelaySeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/health
        #     port: 8000
        #   periodSeconds: 10
        #   failureThreshold: 5
        #   initialDelaySeconds: 3
        resources:
          requests:
            cpu: 25m
          limits:
            cpu: 100m
        envFrom:
          - configMapRef:
              name: tc-app-config
          - secretRef:
              name: tc-app-secret